# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  USER_NAME: ${{ secrets.USER_NAME }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    ui-tests:
        name: ui-tests
        runs-on: ubuntu-latest
        steps:
            - run: echo "$USER_NAME"
            - run: echo $USER_NAME
            - run: echo $env:USER_NAME
            - run: echo "$env:USER_NAME"
            - run: echo "::${USER_NAME}"
